defaults: &defaults
  instagram_client_id: "9b3941f381df411e8b7907efef572898"
  instagram_client_secret: "0a46fae728f848d2b26be1614b0545ec"
  instagram_access_token: "28001022.9b3941f.fddefb15401b4495b8b74d4cb773587e"
  default_image_search_tag: "fanart"
  # If populated, the next three fields will appear at the end of page titles as "application_name - division_name - organization_name"
  application_name: "Fanart Harvester"
  division_name: "dhsi"
  division_url: "http://meridethgarcia.com/division_url"
  organization_name: "University of Michigan"
  meta_description: "a fanart project for a dhsi class"
  base_image_file_dir: "temp/harvested"
  donor_agreement_text: "Thanks for tagging!"
  contact_email: "scriba@umich.edu"
  feed_description: "Description of this feed"
  # Uncomment to enable Google Analytics tracking
  # google_analytics_tracker: "UA-XXXXXXXX-XX"

development:
  <<: *defaults
  # Add or override config options here

test:
  <<: *defaults
  # Add or override config options here

staging:
  <<: *defaults
  # Add or override config options here

production:
  <<: *defaults
  # Add or override config options here
